name: API Test CI/CD
on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许推送分支、创建标签等内容写入操作
      pages: write     # 增强GitHub Pages相关权限
      id-token: write  # 兼容新版GitHub Pages认证

    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 安装 Allure
        run: |
          curl -sLo allure-2.27.0.tgz https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure
          allure --version

      - name: 生成.env配置文件
        run: |
          echo "SERVER_URL=${{ secrets.SERVER_URL }}" >> .env
          echo "PUBLIC_KEY=${{ secrets.PUBLIC_KEY }}" >> .env

      - name: 执行启动程序
        run: |
          python3 start.py
          ls -la

      - name: 部署报告到 Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: report
          publish_branch: gh-pages